---
# force change; remove this line any time
language: python
branches:
  only:
    - master
#TODO: this script could be pulled dynamically
install:
  - pip install -U pip setuptools tox pytest
  - pip install -r requirements.txt
  - npm install jshint
script:
  - ./node_modules/jshint/bin/jshint --config=etc/jshint.conf sirepo/package_data/static/js/{sirepo,elegant,srw,warp}*.js
  - python setup.py pkdeploy
