---
# force change; remove this line any time
language: python
branches:
  only:
    - master
#TODO: this script could be pulled dynamically
install:
  - pip install -U pip setuptools tox pytest
  - pip install -r requirements.txt
  - npm install jshint
script:
  - bash test.sh
