---
sudo: required
services:
  - docker
language: python
branches:
  only:
    - master
install:
  # Avoids Travis running the default install (pip install requirements)
  - true
script:
  - bash travis.sh
